### ISSUE TITLE
Fehlerhafte Spaltenbreite

### ISSUE THREAD

**Issue by bismosa** [HomeAutoUser/Jaro#10]
Hallo!

Um es übersichtlicher zu halten mache ich mal eine neue Issue auf...

Es geht um die Fehlerhafte Spaltenbreite (Siehe ToDo-List).
Bisher haben wir, um die UI anzuzeigen, die "FW_summaryFn" benutzt um statt des Status-Icon die UI mit anzuzeigen.
Dies macht bei bestimmten Designs Schwierigkeiten.
Um dies zu umgehen könnte man die Detail-Ansicht mit dem HTML-Code erzeugen und diese dann extra einblenden lassen:

Detailansicht erzeugen:
`$hash->{FW_detailFn}  = "SD_Keeloq::summaryFn";`
Detailansicht in der Raumansicht hinzufügen
`$hash->{FW_addDetailToSummary} = 1;`
Device-Overview einblenden:
`$hash->{FW_deviceOverview} = 1;`
Es muss die folgende Zeile entfernt werden:
`$hash->{FW_summaryFn}	= "SD_Keeloq::summaryFn";          # displays html instead of status icon in fhemweb room-view`

Siehe auch: https://forum.fhem.de/index.php?topic=71772.0

Dadurch ändert sich das Design geringfügig aber sollte dann auch bei allen FHEM-Designs funktionieren:
Alt:
![image](https://user-images.githubusercontent.com/2944275/62614477-c2790280-b90b-11e9-823b-b57375882420.png)
Neu:
![image](https://user-images.githubusercontent.com/2944275/62614611-11269c80-b90c-11e9-8b02-6d713442a63b.png)

ggf. könnte man nun noch den HTML-Code anpassen, um schmalere Spalten zu bekommen. (Abhängig derzeit von anderen Devices im gleichen Raum)

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
Ich fasse mal deinen Post ebenso kuzr auf.
Sehe ich das richtig, das die Zeile

`$hash->{FW_summaryFn}	= "SD_Keeloq::summaryFn";          # displays html instead of status icon in fhemweb room-view`

entfernt oder auskommentiert werden muss um die richtige Spaltendarstellung (gleichmäßig) zu erziehlen?

MfG

**Comment by bismosa** [comment]
Hallo!

ja, diese muss entfernt oder auskommentiert werden. Sonst wird der HTML-Kram (also die Buttons) doppelt angezeigt.

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
Ich habe es bei uns eingecheckt.

**Comment by bismosa** [comment]
Hallo,

wenn ich da gerade richtig gesehen habe, hast Du nun nur die eine Zeile auskommentiert? Diese Zeilen müssen aber noch hinzugefügt werden:

```
$hash->{FW_detailFn} = "SD_Keeloq::summaryFn";
$hash->{FW_addDetailToSummary} = 1;
$hash->{FW_deviceOverview} = 1;
```

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
Das ging nicht hervor :D

**Comment by bismosa** [comment]
Sorry :)

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
Bitte nochmal kontrollieren
Änderung 1
https://github.com/RFD-FHEM/RFFHEM/pull/623/commits/2a63d61ded3ae72daca7adf59fb45f4a3e3f1855

Änderung 2
https://github.com/RFD-FHEM/RFFHEM/pull/623/commits/e9e62a896d576e803fb3646064be97692e33f6cd

**Comment by bismosa** [comment]
Jup. So sollte es passen :)
DANKE! :)

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
Da nun der Fix eingearbeitet ist und in der Version gefixt, so würde ich den Faden schließen.
Sollte denn noch was sein, einfach ReOpen oder hier weiter schreiben.
