### ISSUE TITLE
Umsetzung für OH mit dem Signalduion ?

### ISSUE THREAD

**Issue by D3ltorohd** [HomeAutoUser/Jaro#5]
Hallo @HomeAutoUser ,

ich wurde durch einen Internet Kontakt auf dieses Projekt aufmerksam geworden. Momentan nutze ich die ursprüngliche Version mit dem ESP - MQTT und OP um meine Rollos zu steuern. Da ich allgemein Neueinsteiger im Bereich Home Automation bin, habe ich mich nun in OH eingearbeitet und dort auch schon einiges in Bezug auf die Rollos geschrieben. Da ich mich schon ein wenig in OH eingearbeitet habe, wollte ich fragen, ob es möglich wäre dein Projekt in Verbindung mit dem Signalduion auch ein Binding für OH zu schreiben ? Da ich mich mit FHEM leider kein bisschen auskenne und eben in OH schon einiges angelegt habe diese Frage. Da ich leider mit der aktuellen HW Lösung Probleme habe, wäre die Sache mit dem Signalduion ohne WLAN eine tolle Alternative. Dann wären die WLAN Verbindungsabbrüche schon mal Geschichte und das ganze sollte eigentlich dann einwandfrei funktionieren.

Grüße und auf jeden Fall auch von mir ein großes Dankeschön, damit du dein Projekt mit uns geteilt hast.

**Comment by HomeAutoUser** [comment]
Guten Tag und vielen Dank für Ihre Worte. Ich kann soeben mit der Abkürzung OH wenig anfangen und bräuchte ein paar Informationen mehr darüber.

Grundsätzlich sollte eine Anbindung an Fhem kein Problem darstellen aber natürlich bedarf es auch viel zu testen wenn man als Schreiber, jeweils nur „virtuell die Fälle durchspielen kann“.

Liebe Grüße :)

**Comment by D3ltorohd** [comment]
Mit OH meinte ich OpenHab2. Oder eben die Möglichkeit vllt über MQTT die Befehle von OpenHab an FHEM zu schicken, das wiederum an den Signalduino. Kenn mich da leider nicht so gut aus.

**Comment by bismosa** [comment]
Hallo!

Eigentlich sollte dies nichts mit dem Modul zu tun haben. Eine Anbindung sollte sich problemlos mit FHEM und mqtt machen lassen.
Bitte dafür mal nachschauen wie man das mit FHEM macht...

Gruß
Bismosa
