### ISSUE TITLE
MQTT Bridge einbauen / Befehle per MQTT senden / empfangen

### ISSUE THREAD

**Issue by D3ltorohd** [HomeAutoUser/Jaro#7]
Ich stehe nun vor einem anderen Problem. Da das hier ja ein FHEM Modul ist und ich mich eigentlich auf OpenHab eingelassen habe, wollte ich mal Fragen ob es hier jemanden gibt, der mir dabei helfen kann, das ganze über eine mqtt Bridge in FHEM per OpenHab zu steuern, dort ist vom original Gateway ja schon alles eingerichtet usw, das würde ich soweit gern weiter nutzen. Leider hat es bis jetzt noch nicht funktioniert. Kenne mich mit FHEM leider überhaupt nicht aus, sonst würde ich da vllt umsteigen. Aber hab bei OH halt schon Thermostate und eben die Rollogeschichte.

Sprich, die Befehle auf / ab / stop über MQTT empfangen und senden. Dann könnte man das mit dem MQTT Broker verbinden und in einer anderen Software (hier z.b. OpenHab) die Rollos über FHEM steuern.

Bei dem original Dongle/Gateway wurde das auch so gelöst, man kann das Gateway per MQTT ansprechen.

Ich hoffe ich habe das verständlich rüber gebracht.

**Comment by bismosa** [comment]
Hallo,

machen wir nun hier weiter....

Ich habe es mal eben ausprobiert (Ich kenne leider OpenHab kaum). Daher fange ich bei so etwas langsam an:
Als erstes benötigt man ein "MQTT" Device. Hier mal meine RAW-Definition:
```
defmod mqtt MQTT localhost:1883
```
Mehr benötigt man hier nicht.

Dann benötigt man zum empfangen (von MQTT Nachrichten) ein MQTT-Device:
```
defmod mqtt_Rollo MQTT_DEVICE
attr mqtt_Rollo IODev mqtt
attr mqtt_Rollo subscribeReading_Rollo1 {fhem("set SD_Rollo_16ch $message")} /jaro
```
Mein SD_Keeloq-Device ist "SD_Rollo_16ch".
Ich habe zum testen jetzt einfach nur den Topic "/jaro" benutzt.
Bei einer kommenden Nachricht setze ich einfach nur den Befehl um. 

Getestet habe ich das in einer SSH-Sitzung:
`mosquitto_pub -h localhost -m "up 9" -t /jaro`
Der Rolladen (Kanal 9) ist sofort (hoch) gefahren. Somit kann über die Nachricht bereits alles festgelegt werden und es benötigt nicht für jeden Kanal/Befehl ein eigenes Topic.

Um zu sehen, was an Nachrichten gesendet und Empfangen wird, kann man so alle Nachrichten in der Konsole anzeigen lassen:
` mosquitto_sub -v -h localhost -p 1883 -t '#'`

Nun muss eigentlich nur noch die Rückmeldung erfolgen....
Dies habe ich über eine "MQTT_BRIDGE" erledigt:
```
defmod mqtt_Bridge_Rollo MQTT_BRIDGE SD_Rollo_16ch
attr mqtt_Bridge_Rollo IODev mqtt
```
Dann einmal auf get mqtt_Bridge_Rollo readings und die anderen Attribute wurden ausgefüllt.

Wenn ich nun etwas betätige, werden die Nachrichten verschickt:
```
/SD_Rollo_16ch/button stop
/SD_Rollo_16ch/channel 9
/SD_Rollo_16ch/counter_send 1107
/SD_Rollo_16ch/LastAction_Channel_09 stop
/SD_Rollo_16ch/channel_control no
```

Also sollte dies eigentlich ohne eine Moduländerung funktionieren.

Gruß
Bismosa

**Comment by D3ltorohd** [comment]
Ich hab keine Ahnung, du bist der zweite bei dem es Funktioniert. Bei mir klappt es nicht. Hab von euch beiden das versucht zu übertragen, keine Chance, es tut sich nichts. Das einzige was läuft ist die MQTT Verbindung.

Kann doch nicht war sein.

**Comment by HomeAutoUser** [comment]
@bismosa,
danke für den ISSUES und das wir das Thema hier dann abhandeln.

Auf jedenfall, wenn das Problem gelöst ist, so würde ich gern die Commandref erweitern um anderen mit MQTT sofort etwas zum lesen zu bieten ;-) ... oder eben das Modul noch ein wenig verfeinern hihi

**Comment by D3ltorohd** [comment]
Also @bismosa und @meier81 haben das schon hinbekommen, zumindest das man per MQTT steuern kann, ich habe von beiden die Sachen umgesetzt, hier geht rein gar nichts. Aber wenn können wir das hier posten und du kannst das mit in die ref aufnehmen.

**Comment by HomeAutoUser** [comment]
1) Die aufnahme in die Ref wäre auf jedenfall ein guter Schachzug denke ich.

2) Konntest du testen, ob überhaupt ein MQTT Befehl bei dir abgesetzt wird mit einem MQTTtool oder mit der Testfunktion?

**Comment by D3ltorohd** [comment]
hab mit mqtt.fx und dem mqtt browser geschaut, da tut sich nichts, ausser ich gebe den Befehl dort direkt ein unter publish, von seiten FHEM tut sich nichts.

**Comment by HomeAutoUser** [comment]
Das klingt nach einem Einrichtungsfehler.

Die Einrichtung wie hier hast du vollzogen? https://github.com/HomeAutoUser/Jaro/issues/7#issuecomment-489310033

Ich habe derzeit hier kein MQTT (noch nicht) aber ich denke, du kannst mal am einfachsten auf der MQTT Bridge glaube auch etwas senden beliebig. Schau mal bitte dort, ob das zumindest dann heraus geht.

**Comment by D3ltorohd** [comment]
Genau, nach dieser Anleitung habe ich das eingerichtet, bis auf das der MQTT Verbindung zum Server hat, wars das schon. Ich weiß nicht was die anderen nutzen, ich nutze in OpenHab2 den eigenen MQTT Server, quasi das Binding MQTT Broker. Mit dem ESP Dongle vom original Projekt ging das über MQTT auch wunderbar.

**Comment by HomeAutoUser** [comment]
Unter der MQTT Bridge gibt es einen Set Befehl
>set <name> publish [qos:?] [retain:?] <topic> <message>
sends message to the specified topic

so kannst du schauen ob du auf jedenfall was senden kannst. Das entnehme ich der Commandref. Werde aber mir mal zum testen einen MQTT mal einrichten.

**Comment by bismosa** [comment]
Hallo!

Ich werde das gefühl nicht los, das vielleicht nur das Perl MQTT fehlt?
Siehe:
https://wiki.fhem.de/wiki/MQTT_Einf%C3%BChrung
```
# Perl Version ausgeben
 perl -v
 # Perl MQTT Module nachinstallieren (läuft ein paar Minuten)
 sudo cpan install Net::MQTT:Simple
 sudo cpan install Net::MQTT:Constants
```

```
Für ältere Distributionen (hier am Beispiel von jessie) muß ggf. aus einer zusätzlichen Paketquelle installiert werden:
wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
sudo apt-key add mosquitto-repo.gpg.key
cd /etc/apt/sources.list.d/
sudo wget http://repo.mosquitto.org/debian/mosquitto-jessie.list
sudo apt-get update
Danach kann die eigentliche Installation durchgeführt werden wie links für stretch beschrieben.
```

Auf welcher Hardware hast Du das Ganze laufen?

Gruß
Bismosa

**Comment by D3ltorohd** [comment]
Hi Bismosa,
das ganze läuft bei mir auf einem Intel NUC5ppyh.
Perl MQTT ist ein MQTT Server ? Ich habe den MQTT Broker von OpenHab am laufen. Somit sollte eigentlich ein MQTT Server vorhanden sein. Mit dem ESP und MQTT klappt das auch wunderbar.

![Screenshot (1051)](https://user-images.githubusercontent.com/2923944/57255225-8788d980-7053-11e9-87d2-10c0d673bd70.png)

**Comment by bismosa** [comment]
Hallo!
NEIN! Es ist kein MQTT Server. Es sind nur die benötigten Module, damit Perl auch MQTT sprechen kann. 
Ich denke, das du deswegen keinerlei Kommunikation bekommst. Ich wundere mich nur, dass es dann keine Logeinträge gibt.
Also bitte mal prüfen, ob die Module vorhanden sind und sonst ggf. installieren.
Gruß
Bismosa

**Comment by D3ltorohd** [comment]
So hab perl 5 drauf, und nun hab ich die Perl MQTT Module nachinstalliert, es kam mal keine Meldung, das ich diese schon hätte. Ich schau dann morgen noch mal ob es jetzt besser aussieht. Wenn die installation durchgelaufen ist, brauche ich das unter # ältere Versionen nicht zu machen ?

**Comment by bismosa** [comment]
Hallo!
Ich denke nicht.
Ich bin die nächsten Tage offline...meine SSD ist vorhin wohl abgeraucht...und mobil kann ich nicht viel machen...
Gruß
Bismosa

**Comment by D3ltorohd** [comment]
Ich versuche mein bestes. Meier81 wird morgen noch mal drüber schauen. Aber wenn das nicht für Perl installiert war, wirds wohl daran gelegen haben. Das war eine frische FHEM Installation für den Signalduino Stick und dieses Jaro Modul. Da ich sonst nichts mit FHEM mache, kann sein das das gefehlt hat, wenn es nicht automatisch mit installiert wird.

**Comment by D3ltorohd** [comment]
So ich habe es hinbekommen. Zumindest kann ich jetzt per mqtt.fx die Rollos fahren lassen. Jetzt muss ich nur noch schauen, warum openhab beim command /JaroFB/Set down 10 einfach nur /JaroFB/set 100 sendet. Aber das ist eine andere Sache, per MQTT steuern funktioniert nun wunderbar. Das ganze nur über eine Bridge und ohne Device.

Für @HomeAutoUser hier mal wie ich die MQTT Bridge nun angelegt habe.

# MQTT Brdige zu OpenHab
define mqtt MQTT 127.0.0.1:1883
setuuid mqtt 5ccecb03-f33f-fc62-0c80-3a84ef68ae5f8109
attr mqtt room MQTT
# MQTT Bridge
define mqtt_Bridge_JaroFB MQTT_BRIDGE JaroFB
setuuid mqtt_Bridge_JaroFB 5cceee3b-f33f-fc62-ab7f-f1cd9bc155139f84
attr mqtt_Bridge_JaroFB IODev mqtt
attr mqtt_Bridge_JaroFB publishReading_LastAction_Channel_01 /JaroFB/LastAction_Channel_01
attr mqtt_Bridge_JaroFB publishReading_LastAction_Channel_02 /JaroFB/LastAction_Channel_02
attr mqtt_Bridge_JaroFB publishReading_LastAction_Channel_03 /JaroFB/LastAction_Channel_03
attr mqtt_Bridge_JaroFB publishReading_LastAction_Channel_04 /JaroFB/LastAction_Channel_04
attr mqtt_Bridge_JaroFB publishReading_LastAction_Channel_05 /JaroFB/LastAction_Channel_05
attr mqtt_Bridge_JaroFB publishReading_LastAction_Channel_06 /JaroFB/LastAction_Channel_06
attr mqtt_Bridge_JaroFB publishReading_LastAction_Channel_07 /JaroFB/LastAction_Channel_07
attr mqtt_Bridge_JaroFB publishReading_LastAction_Channel_08 /JaroFB/LastAction_Channel_08
attr mqtt_Bridge_JaroFB publishReading_LastAction_Channel_09 /JaroFB/LastAction_Channel_09
attr mqtt_Bridge_JaroFB publishReading_LastAction_Channel_1 /JaroFB/LastAction_Channel_1
attr mqtt_Bridge_JaroFB publishReading_LastAction_Channel_10 /JaroFB/LastAction_Channel_10
attr mqtt_Bridge_JaroFB publishReading_LastAction_Channel_11 /JaroFB/LastAction_Channel_11
attr mqtt_Bridge_JaroFB publishReading_LastAction_Channel_12 /JaroFB/LastAction_Channel_12
attr mqtt_Bridge_JaroFB publishReading_button /JaroFB/button
attr mqtt_Bridge_JaroFB publishReading_channel /JaroFB/channel
attr mqtt_Bridge_JaroFB publishReading_channel_control /JaroFB/channel_control
attr mqtt_Bridge_JaroFB publishReading_counter_receive /JaroFB/counter_receive
attr mqtt_Bridge_JaroFB publishReading_counter_send /JaroFB/counter_send
attr mqtt_Bridge_JaroFB publishReading_last_digits /JaroFB/last_digits
attr mqtt_Bridge_JaroFB publishReading_serial_receive /JaroFB/serial_receive
attr mqtt_Bridge_JaroFB publishReading_state /JaroFB/state
attr mqtt_Bridge_JaroFB publishReading_user_info /JaroFB/user_info
attr mqtt_Bridge_JaroFB publishReading_user_modus /JaroFB/user_modus
attr mqtt_Bridge_JaroFB room MQTT
attr mqtt_Bridge_JaroFB subscribeSet /JaroFB/set

**Comment by HomeAutoUser** [comment]
Ich schließe das Thema hier, da das MQTT nicht mit dem Modul selbst was zu tun hat.
Bei Problemen mit dem Modul, einfach neu hier antworten oder ein neues Issues eröffnen.
