### ISSUE TITLE
Anleitung für FHEM ? Gibts keine oder bin ich blind ?

### ISSUE THREAD

**Issue by D3ltorohd** [HomeAutoUser/Jaro#8]
Hallo,
wollte mal nachfragen, ob es hier keine Anleitung oder eine Liste gibt, die zeit was man alles als attr setzten muss und wie man das Modul defined ? Standardmässig ist das ja nicht bei Fhem dabei oder beim Signalduino ? Man muss von Hand die 14_SD_Keeloq in den Ordner opt/fhem/FHEM kopieren ?

Grüße

**Comment by HomeAutoUser** [comment]
Guten Tag,
>Standardmässig ist das ja nicht bei Fhem dabei oder beim Signalduino ?

Das Modul wurde hier entwickelt und befindet sich derzeit mit aktuellem Stand hier:
https://github.com/RFD-FHEM/RFFHEM/tree/dev-r34
Eine Überführung ins reine SVN ist diskussionswürdig.

>Man muss von Hand die 14_SD_Keeloq in den Ordner opt/fhem/FHEM kopieren ?

Jedes Modul muss in deinen genannten Ordner kopiert werden und danach muss ein SHUTDOWN RESTART von FHEM erfolgen.

>ob es hier keine Anleitung oder eine Liste gibt, die zeit was man alles als attr setzten muss und wie man das Modul defined ? 

Attribute werden zum Teil selbst definiert und sind von User zu user unterschiedlich.

Es gibt in jedem Modul eine Commandref wo man nachlesen kann. Wie man das Modul definieren muss ist erläutert wenn man das Modul definieren möchte wie jedes andere.
Dabei erhält man eine Hilfsausgabe. 

`wrong syntax: define <name> SD_Keeloq <Serial> <optional IODEV> `

Das was immer bei jedem Modul hilft, das man mit einem Editor selbst in die Datei schaut und die Commandref am Ende liest.

MfG

**Comment by D3ltorohd** [comment]
Ok, danke dann weiß ich mal bescheid und kann mit deinen Infos nachschauen. Danke dir ! Hatte auf der FHEM Seite im Commanref geschaut aber nichts gefunden.

**Comment by HomeAutoUser** [comment]
Kein Problem :-)
Wenn Fragen Sind, gern den Faden reopen dazu.
